[workspace]
members = [
    "add", "mul", "gcd", "factorial", "fibonacci",
    "modexp", "amm_swap", "voting_power"
]
resolver = "2"

[profile.release]
opt-level = "z"
panic     = "abort"
lto       = true
strip     = true
